### ISSUE TITLE
out of range vector access

### ISSUE THREAD

**Issue by malytomas** [datourat/Gorder#1]
Hi,
I am evaluating your program and I found that it crashes on my test graph.
It does an out of range access to vector.

This is the line that causes the problem:
https://github.com/datourat/Gorder/blob/cc9c4f9b4a561afb13c50798171c3fa67d1f3e7f/Graph.cpp#L536

```c++
outedge[graph[u+1].outstart]
```
If u is last node, then u+1 is the dummy node added to the graph array, and the outstart is one after the last element in the outedge array.

I would very much appreciate if you could have a look at this.
Thanks.

[graph.txt](https://github.com/datourat/Gorder/files/3483962/graph.txt)

**Comment by malytomas** [comment]
I just realized that you only need an address of the one-after-last element.
It can be fixed like this:
```c++
if(binary_search(outedge.data() + graph[u].outstart, outedge.data() + graph[u+1].outstart, v)==false){
```

**Comment by datourat** [comment]
Have you really run into the problem with my original code? I have assigned one more space for the dummy node, https://github.com/datourat/Gorder/blob/cc9c4f9b4a561afb13c50798171c3fa67d1f3e7f/Graph.cpp#L81

**Comment by malytomas** [comment]
I am using microsoft msvc which adds assert into operator [] on vector. It was failing in the outedge vector. The fix with pointer arithmetic removes the call to the [] operator and works fine.
Thanks.

Btw I will be sending you a PR with fixes for msvc soon. I hope you will appreciate it.
